---
- hosts: all
  become: true
  tasks:
  - name: Install Git
    package:
      name: git
      state: present
      
  - name: Run update
    apt:
      update_cache: true
      
  - name: Install jdk
    package:
      name: openjdk-8-jdk
      sate: present
      
  - name: Download Chrome Browser
    command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    
  - name: Install Chrome Browser
    command: apt install ./google-chrome-stable_current_amd64.deb -y
    
  - name: Run update
    apt:
      update_cache: yes
      
  - name: download chromedriver
    command: wget https://chrome-driver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
    
  - name: Install unzip
    command: apt install unzip
    
  - name: Unzip ChromeDriver
    command: unzip chromedriver_linux64.zip
    
  - name: Move chromedriver
    command: mv chromedriver /home/ubuntu/
