---
- hosts: dev
  become: true
  tasks:
  - name: install pip
    packege: 
    name: phthon2-pip
    state: present
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: Pull default Docker image
      docker_image:
        name: "{{ DevEdureka/myphpweb }}"
        source: pull
  - name: Start the Container
      docker_container:
        name: "{{ DevEdureka/myphpweb }}{{ item }}"
        image: "{{ DevEdureka/myphpweb }}"
        command: "{{ docker run --name mywebsitephp -itd -p 1800:80 DevEdureka/myphpweb }}"
        state: started
        published_port:
          - 1800:80
